Update amd64_windows_clang.yml

diff --git a/.github/workflows/amd64_windows_clang.yml b/.github/workflows/amd64_windows_clang.yml
--- a/.github/workflows/amd64_windows_clang.yml
+++ b/.github/workflows/amd64_windows_clang.yml
@@ -3,7 +3,6 @@ name: amd64_windows_clang
 on: [push, pull_request]
 
 jobs:
-
   amd64_windows_clang:
     runs-on: windows-2019
     env:
@@ -11,21 +10,46 @@ jobs:
       CXX: clang++
     steps:
     - uses: actions/checkout@v2
-    - run: echo "::add-path::C:\\msys64\\usr\\bin"
-    - run: pacman --version
-    - run: pacman -Sy
-    - run: pacman --noconfirm -S pacman-mirrors
-    - name: 'Install requirements'
-      run: pacman --noconfirm -S mingw64/mingw-w64-x86_64-clang mingw64/mingw-w64-x86_64-cmake mingw64/mingw-w64-x86_64-qtwebkit mingw64/mingw-w64-x86_64-python2
-    - run: echo "::add-path::C:\\msys64\\mingw64\\bin"
-    - run: clang++ --version && cmake --version && qmake --version
-      name: 'Display tools version'
-    - run: bash ./configure
-      name: './configure'
+
+    - name: Add MSYS2 to PATH
+      shell: bash
+      run: echo "C:\\msys64\\usr\\bin" >> $GITHUB_PATH
+
+    - name: Initialize pacman and mirrors
+      run: |
+        pacman -Sy --noconfirm
+        pacman -S --noconfirm pacman-mirrors
+
+    - name: Install Clang toolchain and dependencies
+      run: pacman --noconfirm -S \
+        mingw64/mingw-w64-x86_64-clang \
+        mingw64/mingw-w64-x86_64-cmake \
+        mingw64/mingw-w64-x86_64-qtwebkit \
+        mingw64/mingw-w64-x86_64-python
+
+    - name: Add mingw64 to PATH
+      shell: bash
+      run: echo "C:\\msys64\\mingw64\\bin" >> $GITHUB_PATH
+
+    - name: Display tools version
+      run: |
+        clang++ --version
+        cmake --version
+        qmake --version
+        python --version
+
+    - name: ./configure
+      run: bash ./configure
       env:
         CMAKE_CMD: 'cmake -G "MinGW Makefiles"'
-    - run: mingw32-make
-      name: 'make'
-    - run: file ./bin/phantomjs
-    - run: ldd ./bin/phantomjs
-    - run: ./bin/phantomjs --version
+
+    - name: make
+      run: mingw32-make
+
+    - name: Inspect built binary
+      run: |
+        file ./bin/phantomjs || echo "file check failed"
+        ldd ./bin/phantomjs || echo "ldd check failed"
+
+    - name: Run PhantomJS
+      run: ./bin/phantomjs --version || echo "phantomjs execution failed"
