Update i686_windows_gcc.yml

diff --git a/.github/workflows/i686_windows_gcc.yml b/.github/workflows/i686_windows_gcc.yml
--- a/.github/workflows/i686_windows_gcc.yml
+++ b/.github/workflows/i686_windows_gcc.yml
@@ -3,28 +3,53 @@ name: i686_windows_gcc
 on: [push, pull_request]
 
 jobs:
-
   i686_windows_gcc:
     runs-on: windows-2019
     env:
       CC: i686-w64-mingw32-gcc
+      CXX: i686-w64-mingw32-g++
     steps:
     - uses: actions/checkout@v2
-    - run: echo "::add-path::C:\\msys64\\usr\\bin"
-    - run: pacman --version
-    - run: pacman -Sy
-    - run: pacman --noconfirm -S pacman-mirrors
-    - name: 'Install requirements'
-      run: pacman --noconfirm -S mingw-w64-cross-toolchain mingw32/mingw-w64-i686-cmake mingw32/mingw-w64-i686-qtwebkit mingw32/mingw-w64-i686-python2
-    - run: echo "::add-path::C:\\msys64\\mingw32\\bin"
-    - run: i686-w64-mingw32-gcc --version && cmake --version && qmake --version
-      name: 'Display tools version'
-    - run: bash ./configure
-      name: './configure'
+
+    - name: Add MSYS2 to PATH
+      shell: bash
+      run: echo "C:\\msys64\\usr\\bin" >> $GITHUB_PATH
+
+    - name: Update pacman and mirrors
+      run: |
+        pacman -Sy --noconfirm
+        pacman -S --noconfirm pacman-mirrors
+
+    - name: Install i686 toolchain and dependencies
+      run: pacman --noconfirm -S \
+        mingw32/mingw-w64-i686-toolchain \
+        mingw32/mingw-w64-i686-cmake \
+        mingw32/mingw-w64-i686-qtwebkit \
+        mingw32/mingw-w64-i686-python
+
+    - name: Add mingw32 to PATH
+      shell: bash
+      run: echo "C:\\msys64\\mingw32\\bin" >> $GITHUB_PATH
+
+    - name: Display tools version
+      run: |
+        i686-w64-mingw32-gcc --version
+        cmake --version
+        qmake --version
+        python --version
+
+    - name: ./configure
+      run: bash ./configure
       env:
         CMAKE_CMD: 'cmake -G "MinGW Makefiles"'
-    - run: mingw32-make
-      name: 'make'
-    - run: file ./bin/phantomjs
-    - run: ldd ./bin/phantomjs
-    - run: ./bin/phantomjs --version
+
+    - name: Build PhantomJS
+      run: mingw32-make
+
+    - name: Inspect built binary
+      run: |
+        file ./bin/phantomjs || echo "file check failed"
+        ldd ./bin/phantomjs || echo "ldd check failed"
+
+    - name: Run PhantomJS
+      run: ./bin/phantomjs --version || echo "phantomjs execution failed"
